basic_settings:
  site_title: Lee Lab
  favicon_image: /images/favicon.png

header_settings:
  logo_image: /images/logo.png
  logo_width: 100

menu_settings:
  menu_items:
    - title: 'Research'
      url: '/'
    - title: 'People'
      url: '/people'
    - title: 'Publications'
      url: '/publications'
    - title: 'Lab Life'
      url: '/lab-life/'
    - title: 'Code of Conduct'
      url: '/code-of-conduct'
    - title: 'Contact'
      url: '/contact'
    - title: 'Join'
      url: '/join'

footer_settings:
  footer_tagline: '
  <strong>Department of Molecular Biology and Biochemistry, Simon Fraser University</strong><br>
  <br>
  <strong>Address:</strong><br>
  Department of Molecular Biology and Biochemistry<br>
  Simon Fraser University<br>
  South Sciences Building Room 8166<br>
  8888 University Drive<br>
  Burnaby, B.C.<br>
  Canada V5A 1S6<br>
  <br>
  <strong>Email:</strong><br>
  ahl23 at sfu dot ca<br>
  <br><a href="/contact/">Contact us</a><br>'

hero_settings:
  overlay_opacity: 0.5
post_settings:
  grid_spacing: 10

social_settings:
  facebook_url: ''
  twitter_url: 'https://twitter.com/minisciencegirl'
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: 'https://github.com/SFU-Lee-Lab'
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: 'https://ca.linkedin.com/in/amy-huei-yi-lee-ph-d-72362535'

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  text_link_color: '#3498db'
  accent_color: '#76c2f5'
  border_color: '#dddddd'
  hero_background_color: '#132930'
  hero_text_color: '#ffffff'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Muli:300,400,600,700" rel="stylesheet">'
  title_font: '"Muli", sans-serif'
  body_font: '"Muli", sans-serif'
  regular_weight: 400
  bold_weight: 600
  bold_weight_strong: 700
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 33
    large_size: 44  # 30
    weight: 700
    letter_spacing: -0.03
    line_height: 1.2
  h2:
    small_size: 16
    medium_size: 22
    large_size: 25
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 16
    medium_size: 18
    large_size: 22
    weight: 600
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 12
    medium_size: 16
    large_size: 16
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 12
    medium_size: 14
    large_size: 15
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 12
    medium_size: 15
    large_size: 15
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 13
    medium_size: 15
    large_size: 16
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

people:
  row_spacing: 30
  minimum_table_length: 200
  headshot:
    length: 175
    border_radius: 10
  about:
    line_height: 25
  blank_headshot_image_path: /images/people/blank-headshot.png

gallery:
  image_width: 700
  image_height: 600

urls:
  google_scholar: https://scholar.google.com/citations?hl=en&user=Ub2zal8AAAAJ

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
